### ISSUE TITLE
Puerto Rico "disappeared"?!?

### ISSUE THREAD

**Issue by MarkoSchuetz** [pwr22/covbot#54] opened 2020-08-16 03:26 UTC
I used to be able to get data on Puerto Rico using 
`!cases Puerto Rico` 
As of today "My data doesn't seem to include...."
Worked like a charm on Thursday.

**Comment by th0mcat** [comment] 2020-08-22 17:47
It looks like data for all US States/Territories is no longer working.  I can confirm Wisconsin, Minnesota, and Florida do not work.

**Comment by pwr22** [comment] 2020-08-22 19:08
Hmmm, that's not ideal! Thanks for letting me know - I'll take a look

**Comment by th0mcat** [comment] 2020-09-28 14:30
I already put this in the covbot Matrix room, but I figured I'd post it here as well.

 I've figured out what's wrong with the Offloop US data, and I know what can fix it, but since I suck at programming/python, I don't know how to do it myself. For some reason, Offloop's unconfirmed.csv did away with State/Territory names (under the 'Province' column) and assigned them numbers. I figured out which number works for which State/Province and put them into a csv. The bot just needs to lookup and match the 'Province' number with the State name.

```
Country,Province,State,Offloop,Worldometers,Worldometers = Offloop?
US,4,New York,33185,33185,Yes
US,8,New Jersey,16201,16201,Yes
US,2,Texas,15373,15373,Yes
US,1,California,15259,15259,Yes
US,3,Florida,13618,13618,Yes
US,18,Massachusetts,9328,9328,Yes
US,6,Illinois,8744,8744,Yes
US,12,Pennsylvania,8130,8130,Yes
US,17,Michigan,7013,7013,Yes
US,5,Georgia,6773,6773,Yes
US,7,Arizona,5525,5525,Yes
US,11,Louisiana,5407,5407,Yes
US,14,Ohio,4702,4702,Yes
US,33,Connecticut,4497,4497,Yes
US,19,Maryland,3902,3902,Yes
US,21,Indiana,3530,3530,Yes
US,9,North Carolina,3316,3316,Yes
US,57,Veteran Affairs,3310,3310,Yes
US,16,South Carolina,3262,3262,Yes
US,15,Virginia,3089,3089,Yes
US,23,Mississippi,2870,2870,Yes
US,13,Alabama,2488,2488,Yes
US,10,Tennessee,2275,2275,Yes
US,20,Missouri,2083,2083,Yes
US,25,Washington,2059,2059,Yes
US,24,Minnesota,2037,2037,Yes
US,30,Colorado,2025,2025,Yes
US,29,Nevada,1556,1556,Yes
US,26,Iowa,1294,1294,Yes
US,22,Wisconsin,1259,1259,Yes
US,28,Arkansas,1229,1229,Yes
US,32,Kentucky,1119,1119,Yes
US,39,Rhode Island,1102,1102,Yes
US,27,Oklahoma,970,970,Yes
US,38,New Mexico,854,854,Yes
US,40,Delaware,629,629,Yes
US,34,Kansas,621,621,Yes
US,43,District Of Columbia,621,621,Yes
US,52,Puerto Rico,617,617,Yes
US,59,Navajo Nation,548,548,Yes
US,37,Oregon,537,537,Yes
US,35,Nebraska,461,461,Yes
US,36,Idaho,451,451,Yes
US,31,Utah,444,444,Yes
US,47,New Hampshire,438,438,Yes
US,44,West Virginia,319,319,Yes
US,42,North Dakota,203,203,Yes
US,41,South Dakota,202,202,Yes
US,46,Montana,165,165,Yes
US,49,Maine,140,140,Yes
US,58,Federal Prisons,124,124,Yes
US,45,Hawaii,120,120,Yes
US,56,US Military,94,94,Yes
US,51,Vermont,58,58,Yes
US,50,Wyoming,49,49,Yes
US,48,Alaska,45,45,Yes
US,53,Guam,37,37,Yes
US,54,United States Virgin Islands,19,19,Yes
US,60,Grand Princess Ship,3,3,Yes
US,55,Northern Mariana Islands,2,2,Yes
US,61,,0,,Yes
```

**Comment by pwr22** [comment] 2020-09-28 14:37
Sorry, still haven't had time to look at this yet. Will try to get to it
tonight. I'll also ask the author of offloop why it happened.

**Comment by th0mcat** [comment] 2020-09-28 14:39
No worries at all!

I've also been trying to touch base with the author as well to see if it can be fixed on their end, but I can't find any contact information or even a public git repo.

**Comment by pwr22** [comment] 2020-09-28 20:42
I'm working on a fix now using your mapping @thomcatdotrocks. I've also let the offloop author know in IRC.

Edit: Any idea what that number 61 is there?

**Comment by pwr22** [comment] 2020-09-28 21:02
Well I got a fix but it's fixed upstream now so no worries!

**Closed as completed by pwr22** 2020-09-28 21:02 UTC
